"""Fixed async migration

Revision ID: 0923d6a94852
Revises: 
Create Date: 2025-02-09 15:13:13.463905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0923d6a94852'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('document_name', sa.String(), nullable=False))
    op.drop_index('ix_documents_name', table_name='documents')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_column('documents', 'name')
    op.add_column('training_progress', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_training_progress_user_name', table_name='training_progress')
    op.create_foreign_key(None, 'training_progress', 'users', ['user_id'], ['id'])
    op.drop_column('training_progress', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_progress', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training_progress', type_='foreignkey')
    op.create_index('ix_training_progress_user_name', 'training_progress', ['user_name'], unique=False)
    op.drop_column('training_progress', 'user_id')
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index('ix_documents_name', 'documents', ['name'], unique=False)
    op.drop_column('documents', 'document_name')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
